### ISSUE TITLE
locales issue on MacOS

### ISSUE THREAD

**Issue by arademaker** [TALP-UPC/FreeLing#10]
The analyze program is having trouble with encoding.

```
urca:~ arademaker$ echo 'testando situação.' | analyze -f pt.cfg
testando testar VMG0000 1
situa� situa� RG 0.365785
� � Fz 1
� � NP00000 1
� � Fz 1
o o DA0MS0 0.950254
. . Fp 1
```

The locale command returns:

```
urca:~ arademaker$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

The config file used says:

```
urca:~ arademaker$ head /usr/local/share/freeling/config/pt.cfg
##
#### default configuration file for Portuguese analyzer
##

#### General options
Lang=pt
Locale=en_US.UTF-8
```

**Comment by lluisp** [comment]
That looks as if the terminal input is ISO, not UTF8

Try using a text file you can make sure it is utf8
```
$ echo "testando situação." > my.txt
$ file my.text
my.txt: UTF-8 Unicode text
```
If you get 
```
$ file my.text
my.txt: ISO-8859 text
```
Then, convert it to utf8
```
$ iconv -f iso-8859-1 -t utf8 <my.txt  >my.utf8.txt
$ file my.text
my.txt: UTF-8 Unicode text
```

and analyze the file (not the tty input):
$ file my.text
```
analyze -f pt.cfg  < my.utf.txt
```

**Comment by arademaker** [comment]
Same problem with "<":

```
$ cat teste.txt

Testando a situação.

urca:Temp arademaker$ file teste.txt
teste.txt: UTF-8 Unicode text
urca:Temp arademaker$ analyze -f pt.cfg < teste.txt
Testando testar VMG0000 1
a o DA0FS0 0.675415
situa? situa? NCFS000 0.536511
? ? Fz 1
? ? NP00000 1
? ? Fz 1
o o DA0MS0 0.950254
. . Fp 1
```

This is strange!

**Comment by lluisp** [comment]
Yes, I can't understand what is happening.
Maybe @ambs, who is also on Mac, can enlighten us...

**Comment by lluisp** [comment]
try setting `Locale=default` in the config file

**Comment by ambs** [comment]
Will try to look into it.

**Comment by arademaker** [comment]
@lluisp , ```Locale=default``` does work either: 

```
$ analyze -f pt.cfg < teste.txt
Testando testar VMG0000 1
a o DA0FS0 0.675415
situa� situa� NCFS000 0.536511
� � Fz 1
� � NP00000 1
� � Fz 1
o o DA0MS0 0.950254
. . Fp 1

**Comment by ambs** [comment]
Having same problem. Both with freeling 3.1 and 4.0. 
If I recall correctly, I've sent some emails regarding this some time ago, for freeling 3. But then, using the Swig interface did not have more problems with that.

**Comment by ambs** [comment]
@arademaker, as a workaround meanwhile

````
    iconv -f utf8 -t latin1 < yourtextinutf > yourtextinlatin1
    analyze [options]  <yourtextinlatin1 >yourresultinlatin1
    iconv -f latin1 -t utf8 < yourresultinlatin1 > yourresultinutf8
````
not optimal, but works meanwhile :-) will try to help @lluisp, but that might take some time.

**Comment by ambs** [comment]
Just to make things more confusing, in `util.cc` I added:
````
#undef USE_BOOST_LOCALE
````
and... it compiles... and... exactly the same result. Either not specifying locale, or setting it as default, or exactly to pt_PT.UTF-8.

**Comment by lluisp** [comment]
In 3.1, using boost_locale was the only way to have it work on Mac... So I'm not sure is a good idea to disable it.

If the commands you suggest work, then it means that FreeLing is doing I/O in latin1...
Since the dictionaries are in UTF8, any word with special characters should not be found in the dictionary, unless the locale library performs automatically the conversion...

I don't know how a Russian text could be analyzed, then...  :-S

**Comment by arademaker** [comment]
The command that @ambs suggested worked:

```
urca:Temp arademaker$ iconv -f utf-8 -t latin1 < teste.txt > testelatin1
urca:Temp arademaker$ analyze -f pt.cfg < testelatin1 > teste.out.latin1
urca:Temp arademaker$ iconv -f latin1 -t utf-8 < teste.out.latin1 > teste.out
urca:Temp arademaker$ cat teste.out
Testando testar VMG0000 1
a o DA0FS0 0.675415
situação situação NCFS000 1
. . Fp 1
```

**Comment by ambs** [comment]
@lluisp, I can't promise to give any answer quickly, but I'll try to understand what is going on.
Not sure if you plan to release freeling 4 soon. If not, then maybe I can try to find a solution before the release.

**Comment by arademaker** [comment]
Guys, I would love to help you more if you switch for Common Lisp instead of C++! ;-)

**Comment by lluisp** [comment]
@ambs: I plan to release it in early/mid May.  
In the worst case, I could include some "analyzer-mac" script that makes the encoding and decoding.

@arademaker:  Common what??  A guy your age shouldn't know about these things... :-P

**Comment by ambs** [comment]
ok, will try to find out if I can help.
@arademaker, I could help better if it would be Perl, but C/C++ is tolerable.

**Comment by lluisp** [comment]
The problem is not the language, but the operating system and locale management.

**Comment by ambs** [comment]
My knowledge of C++ is limited. I know C, but not much experience with wchar and wstring. Any way, I was expecting a wstring to be an array of wchars, and expecting each wchar to be one or two bytes (or four), depending on the UTF-8 input.

I tried this change in the analyzer code:
``````
int ReadLine(wstring &text) {
  int n=0;
  if (ServerMode) {
    string s;
    n = sock->read_message(s);
    text = util::string2wstring(s);
  }
  else {
    if (getline(wcin,text)) {n=1;
       for (int i=0; i< text.length(); i++) {
          wcerr << text.at(i);
          cerr << "\n";
       }
    wcerr << text;}
  }

  return n;
}
`````
Is this expected to print each UTF-8 char in its own line? If the answer is "yes", I have bad news, as t this point I get a byte per line (not a char). Will try to get a Linux machine to test in, but meanwhile if you can comment on this test, I am thankful.

**Comment by ambs** [comment]
Just tested the above in a linux system, and I get one char per line. So it seems `getline` isn't working properly. Is this a C++ function?

**Comment by ambs** [comment]
This needs some work, but I am getting interesting results.
This function works both on Mac and Linux.
``````
int ReadLine(wstring &text) {
  int n=0;
  if (ServerMode) {
    string s;
    n = sock->read_message(s);
    text = util::string2wstring(s);
  }
  else {
    string s;
    if (getline(cin,s)) {n=1;
text = util::string2wstring(s);
  }

  return n;
}

``````
The output I am getting in linux:
```````
O o DA0MS0 0.950254
coração coração NCMS000 1
é ser VMIP3S0 1
um um DI0MS0 0.877848
órgão órgão NCMS000 1
frágil frágil AQ0CS00 1
. . Fp 1
`````
The result obtained in mac:
``````
O cora��o � um �rg�o fr�gil.O o DA0MS0 0.950254
cora��o cora��o NCMS000 1
� ser VMIP3S0 1
um um DI0MS0 0.877848
�rg�o �rg�o NCMS000 1
fr�gil fr�gil AQ0CS00 1
. . Fp 1
`````
So, at the moment it seems it is an output issue.

@lluisp, would you accept a patch to replace all getline( wcin, something) to this combo? (read from cin, convert to utf8).

I imagine a similar approach needs to be done for the output. But will wait for your comments.

**Comment by ambs** [comment]
Ah, btw, redirected the output to a file, and it is.... iso-8859-1 encoded. :open_mouth:

**Comment by ambs** [comment]
This doesn't help much, but is something I found confusing in the Boost Locale documentation, and as such, I share it here:

# Myths
## To use Unicode in my application I should use wide strings everywhere.

Unicode is not limited to wide strings. Both `std::string` and `std::wstring` can hold and process Unicode text. More than that, the semantics of `std::string` are much cleaner in multi-platform applications, because all "Unicode" strings are UTF-8. "Wide" strings may be encoded in "UTF-16" or "UTF-32", depending on the platform, so they may be even less convenient when dealing with Unicode than char based strings.

**Comment by lluisp** [comment]
It is true that you can store unicode characters inside a string (and not a wstring) and input/output will work the same, because at that level, strings are just byte sequences. 
But this has some limitations that are vital in FreeLing:
* string::length will give the number of bytes and not the number of characters (that will not necessarily be the same)
* regexps containing non-basic-ascii characters (such as á,é,ñ,ü, or any russian character) will fail to match the input
* basic locale functions such as `is_upper`, or `is_letter` will fail to work.

So, changing wstring to string is not an option

  Your suggestion of changing wcin to cin, and then do string2wstring is a possible workaround (at least for mac version), but is not the proper way.
  All this code used to work in older Mac versions (I remember fighting with locale libraries to get it to work, until I found that boost::locale would do the job for Mac), so the answer should not be in changing freeling (or your example program) but in using the appropriate locale library or compiler setting.

 Note that freeling has this util::init_locale function that must be called at the beggining of each program. This is not freeling-specific.  It just sets the locale so C++ will manage utf8.
Without it, C++ will not read utf8 input (at least until now... maybe newer compiler versions are native in utf8...).
So, you should test your example program with this line at the beggining and see what happens...

**Comment by ambs** [comment]
I am changing directly the analyzer code, so the code calling locale is there.
Regarding freeling working previously on Mac, probably it did. But I have 3.1 installed, and analyze in the command line will not work.

I am not suggesting changing back to string instead of wstring. Just trying to understand, and I think that adding my findings here might help as you can go and comment on them, so working like som kind of "brainstorming".

I am at the moment hanging in libboost irc channel trying to find out what we are doing wrong.

Good weekend ;)

**Comment by usrenmae** [comment]
Hi. Having the similar issue here with `brew install`-ed FreeLing 3.1.8. My symptoms are the following:
- default configuration file (tried both Locale: default and es_ES.utf8)
- input file has utf8-encoded special chars
- analyzer -f config.ini < input.file > output.file
- output file has broken characters, which are supposed to be utf8 encoded.
As far as I can see, only the first byte of each utf8 character present in output. The second byte is just missing. 
```
$ echo 'más' > input.txt
$ hexdump input.txt
0000000 6d c3 a1 73
0000004
$ grep Locale config.ini
Locale=es_ES.utf8
$ analyzer -f config.ini < input.txt > output.txt
$ less output.txt
m<C3> m<E3> RG 0.106203
<A1> <A1> Faa 1
s segundo NCMN000 0.62232

output.txt (END)
$ hexdump -C output.txt
00000000  6d c3 20 6d e3 20 52 47  20 30 2e 31 30 36 32 30  |m. m. RG 0.10620|
00000010  33 0a a1 20 a1 20 46 61  61 20 31 0a 73 20 73 65  |3.. . Faa 1.s se|
00000020  67 75 6e 64 6f 20 4e 43  4d 4e 30 30 30 20 30 2e  |gundo NCMN000 0.|
00000030  36 32 32 33 32 0a 0a                              |62232..|
00000037
$ cat output.txt
m� m� RG 0.106203
� � Faa 1
s segundo NCMN000 0.62232
```

So, as seen the trailing "s" character has disappeared, and only the first part of the "á" character - <C3> is left.

**Comment by ambs** [comment]
Working on a fix for Mac. Look for https://github.com/ambs/FreeLing/tree/mac-locale developments. When It's done, I'll comment here.

**Comment by ambs** [comment]
Dear @arademaker, can you please checkout this branch and try it in your mac?
https://github.com/ambs/FreeLing/tree/mac-locale

Just to make sure it works in more than one machine :) thanks

**Comment by usrenmae** [comment]
@ambs 
Works ok on my mac when compiling from `mac-locale` branch. Great job.

**Comment by ambs** [comment]
@usrenmae did you try to run analyze, just to be sure it works with unicode? Thanks

**Comment by usrenmae** [comment]
@ambs yes indeed, i did try the same test with `más` and it worked ok.

**Comment by ambs** [comment]
Yay. Great.
@lluisp, I think it is safe to merge. But I have a bunch of code on configure.ac commented out. Do you want me to remove it first?

**Comment by usrenmae** [comment]
I found it also useful to include `-j` into `make` command inside `autogen.sh` - https://github.com/TALP-UPC/FreeLing/blob/master/autogen.sh#L24 to make use of multi-core systems and boost up the compilation.

**Comment by lluisp** [comment]
@ambs:  Yes, please remove unneeded code, and I'll merge it in.

**Comment by lluisp** [comment]
@usrenmae: adding `-j` is dangerous since there is no limit on the parallel jobs it will create, and there are dozens of files to compile.
For instance, my machine has 8 processors and 8Gb of RAM
If I run `make -j 8` I get 8 parallell compiles, and everything is fine.
If I run `make -j 16` I get 16 parallell compiles, and RAM get so full that the computer is on the edge of trashing.
But if I run `make -j` (with no limit), it uses so many resources that the computer freezes in a couple of seconds.

So, to add this option, one should set a limit, But if we set the limit to e.g. 4, people with less RAM or less processors will get their machines frozen... 

So, I'd prefer to leave the decision of adding `-j` to each user.

**Comment by arademaker** [comment]
@ambs worked! 

```
$ echo 'meu coração bate forte quando Freeling funciona!' | analyze -f pt.cfg
meu meu DP1MSS 0.99505
coração coração NCMS000 1
bate bater VMIP3S0 0.223029
forte forte RG 0.0827068
quando quando RG 0.998992
Freeling freeling NP00000 1
funciona funcionar VMM02S0 0.0238095
! ! Fat 1
```

**Comment by lluisp** [comment]
python example calls init_locale at the begginig, so it should work ok.

**Comment by ambs** [comment]
I think this thread can be now closed :-)
