### ISSUE TITLE
Problem generating Java APIs

### ISSUE THREAD

**Issue by AAAton** [TALP-UPC/FreeLing#46]
Hi!
I've been trying to get the Java APIs to work, and have been following the instructions, but I was unable to generate the files on OS/X as well as on Ubuntu, with identical error messages. I am most likely doing something wrong, but I can't seem to figure out what. 

Output when running make: 

```
rm -rf edu/upc/freeling
mkdir -p edu/upc/freeling
mkdir -p /usr/local/
swig -java -c++ -package edu.upc.freeling -outdir edu/upc/freeling -o freeling_javaAPI.cxx -I/usr/local/share/swig/3.0.12/java -I/usr/local/share/swig/3.0.12/std -I/usr/local/share/swig/3.0.12 freeling_javaAPI.i
/usr/local/share/swig/3.0.12/std/std_set.i:98: Error: Syntax error in input(3).
make: *** [freeling_javaAPI.cxx] Error 1
```

I have tried using both swig2.0 and the newest version without avail. 

std_set.i:98 (if relevant): ` %fragment(SWIG_Traits_frag(std::set< _Key, _Compare, _Alloc >), "header",fragment=SWIG_Traits_frag(_Key), fragment="StdSetTraits")` 

Any help is appreciated.

**Comment by lluisp** [comment]
I seems swig does not include a Java API for std::set (should be in /usr/local/share/swig/3.0.12/java/std_set.i)  and it was trying to use /usr/local/share/swig/3.0.12/std/std_set.i  (which I don't kwno what it is... question for swig guys, I guess).

 FreeLing 4.0 API uses std::set in some places (e.g. in language identifier results) and that is why the error.
I added conditional compilation for the APIs so that std::set is excluded from Java API

get latest APIs/common/templates.i and it should work (as long as you don't use classes with std::set in the parameters or results)

**Comment by AAAton** [comment]
Thank you for the response. That is how I have understood it as well when I was googling around. on std_set.i and java. 

I will try to recompile it with the latest commits.
